### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by fri-end** [gipit/gippy#112]
I'm getting this error when trying to install gippy: command 'x86_64-linux-gnu-gcc' failed with exit status 1, after running `sudo python setup.py install`

> running install
> DEBUG:setup.py:_install finalize_options
> DEBUG:setup.py:_install run
> running build_ext
> DEBUG:setup.py:_build_ext run
> building 'gippy/libgip' extension
> x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -IGIP -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/gdal -I/usr/include/python2.7 -c GIP/GeoAlgorithms.cpp -o build/temp.linux-x86_64-2.7/GIP/GeoAlgorithms.o -fPIC -O3 -std=c++11 -Wno-maybe-uninitialized
> x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -IGIP -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/gdal -I/usr/include/python2.7 -c GIP/GeoVectorResource.cpp -o build/temp.linux-x86_64-2.7/GIP/GeoVectorResource.o -fPIC -O3 -std=c++11 -Wno-maybe-uninitialized
> GIP/GeoVectorResource.cpp: In constructor 'gip::GeoVectorResource::GeoVectorResource(std::string, std::string)':
> GIP/GeoVectorResource.cpp:37:30: error: 'Open' is not a member of 'OGRSFDriverRegistrar'
>          _OGRDataSource.reset(OGRSFDriverRegistrar::Open(filename.c_str()), OGRDataSource::DestroyDataSource);
>                               ^
> GIP/GeoVectorResource.cpp:37:91: warning: 'static void OGRDataSource::DestroyDataSource(OGRDataSource*)' is deprecated (declared at /usr/include/gdal/ogrsf_frmts.h:245) [-Wdeprecated-declarations]
>          _OGRDataSource.reset(OGRSFDriverRegistrar::Open(filename.c_str()), OGRDataSource::DestroyDataSource);
>                                                                                            ^
> GIP/GeoVectorResource.cpp: In member function 'gip::BoundingBox gip::GeoVectorResource::extent() const':
> GIP/GeoVectorResource.cpp:99:38: warning: ignoring return value of function declared with attribute warn_unused_result [-Wunused-result]
>          _Layer->GetExtent(&ext, true);
>                                       ^
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Could anyone help me to resolve this?

**Comment by ircwaves** [comment]
I believe that sounds like you have installed gdal 2.0 dev.  Check:
```shell
ircwaves@north $ gdal-config --version
1.11.3
```
gippy needs libgdal-dev 1.x.

**Comment by matthewhanson** [comment]
hello @fri-end , it does indeed sound like the problem is it's being compiled with GDAL2.   I did have a preliminary gdal 2.0 branch, which required just a few adjustments:
https://github.com/gipit/gippy/tree/gdal2

When I get a chance I'd like to have it work with either GDAL 1 or 2, which will require some compilation flags to check, since there are some significant changes to the underlying GDAL classes.

**Comment by fri-end** [comment]
Indeed @ircwaves , my gdal version is 2.1.0.
@matthewhanson, please let me if you manage to make gippy to work with GDAL 2.
Cheers

**Comment by matthewhanson** [comment]
Resolved on develop
