### ISSUE TITLE
support GDAL SetGeotransform or equivalent

### ISSUE THREAD

**Issue by bhbraswell** [gipit/gippy#16]
I typically construct geo-image data by specifying an array, a projection, and a geotransform. This could be handled in gippy with the existing constructors if there was a method to set the geotransform (as in GDAL), or separate methods to set spatial resolution, and UL X and Y coordinates.

**Comment by ircwaves** [comment]
`GeoImage.SetAffine` accepts the GDAL style geotransform array.  Does that help?

**Comment by bhbraswell** [comment]
Probably, I'll check it out. Sorry I missed it.

**Comment by bhbraswell** [comment]
This feature comes via the GeoResource.
