### ISSUE TITLE
GIP/gip/GeoResource.h:32:28: fatal error: gdal/gdal_priv.h: No such file or directory

### ISSUE THREAD

**Issue by bmoskovi** [gipit/gippy#19]
I am using GDAL version 1.11.2 and  gdal_priv.h is located at ./gdal1.11.2/gcore/gdal_priv.h.  When I compile gippy, I get this compiler error:

~/dev/gis/gippy$ python setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/gippy
copying gippy/version.py -> build/lib.linux-x86_64-2.7/gippy
copying gippy/__init__.py -> build/lib.linux-x86_64-2.7/gippy
running build_ext
building 'gippy/libgip' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/GIP
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -IGIP -I/usr/include/python2.7 -c GIP/GeoImage.cpp -o build/temp.linux-x86_64-2.7/GIP/GeoImage.o -std=c++11 -O3 -DBOOST_LOG_DYN_LINK
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from GIP/gip/GeoImage.h:25:0,
                 from GIP/GeoImage.cpp:22:
GIP/gip/GeoResource.h:32:28: fatal error: gdal/gdal_priv.h: No such file or directory
 #include <gdal/gdal_priv.h>
                            ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by matthewhanson** [comment]
Hi, this looks like python-gdal is not installed. 

If you were installing this as part of lidar2dems using the easy-install script there were some missing dependencies (it's been updated now).

Here's the new list of libs to install via apt-get:
sudo apt-get install git cmake g++ libboost-all-dev libgdal1-dev libeigen3-dev libflann-dev libopenni-dev libvtk5.8-qt4 libqhull-dev qt-sdk libvtk5-qt4-dev libpcap-dev python-vtk libvtk-java python-numpy libgeotiff-dev python-setuptools swig swig2.0 python-gdal python-scipy libxslt1-dev

matt

**Comment by bmoskovi** [comment]
Hi Matt, I installed GDAL from source since python-gdal under Ubuntu 14.04.2 only has GDAL 1.10.1 and I need 1.11.2.  For some reason /usr/local/include/gdal_priv.h is not being used.  I see python-gdal has gdal_priv.h located at /usr/include/gdal/gdal_priv.h.  So I don't know why it is not being picked up.

**Comment by matthewhanson** [comment]
The include statement for gdal_priv.h in GIPPY is

    #include <gdal/gdal_priv.h>

because the standard header install location (and how I've seen it included in other programs) is under a gdal subdirectory in the include path.   Two simple solutions:

1 - if you manually installed the files, move the gdal headers into a gdal subdir in /usr/local/include (or /usr/include).

2 - make a gdal symbolic link in the include directory that points to the same directory:

     /usr/include $ sudo ln -s ./ gdal

So when it looks for gdal/gdal_priv.h it will find it as the gdal symbolic link points to the right directory.
