### ISSUE TITLE
GeoVector where/ SQL problem 

### ISSUE THREAD

**Issue by bhbraswell** [gipit/gippy#22]
mcorbier wrote:

mcorbier@rio:/titan/work/mcorbiere/geokit$ gips_project daymet -s gadmn2_vtnh.shp -d 2010 --days 100,105 -k OBJECTID -p tmax -w "HASC_1=US.NH" 

GIPS Data Project (v0.8.0rc6) Data Project error: GeoVector_where() takes exactly 3 arguments (2 given)

The -w clause needs 3 arguments, which is not possible to write on the command line as far as I can tell. The new version of GIPS also does not allow for anything other than an =, making it less useful than the old sql string version.mcorbier@rio:/titan/work/mcorbiere/geokit$ gips_project daymet -s gadmn2_vtnh.shp -d 2010 --days 100,105 -k OBJECTID -p tmax -w "HASC_1=US.NH" GIPS Data Project (v0.8.0rc6) Data Project error: GeoVector_where() takes exactly 3 arguments (2 given)

The -w clause needs 3 arguments, which is not possible to write on the command line as far as I can tell. The new version also does not allow for anything other than an =, making it less useful than the old sql string version.

**Comment by matthewhanson** [comment]
You appear to be using an older version of GIPPY that does not include the where(sql) functionality.   Upgrade with

pip install --upgrade gippy
