### ISSUE TITLE
Add SetRGB method to GeoImage

### ISSUE THREAD

**Issue by scisco** [gipit/gippy#46]

**Comment by matthewhanson** [comment]
I would say this is actually fully fixed.  There is no SetRGB function, but it sets the color interpretation flag for each band in the file based on the bandname, so if you set a band to red it's colorinterp flag is Red. Although QGIS doesn't set the colors properly, the bands are clearly indicated as the right colors in the band selection.

QGIS sets colors solely on index, so RGBA must be in that order.    As such, the select function (currently called prune) will serve the same purpose:

select(['red', 'green', 'blue'])

which will reorder the bands.

**Comment by scisco** [comment]
@matthewhanson how are we going to handle the case where a custom color table is needed e.g. when we need a colorful NDVI image?

**Comment by matthewhanson** [comment]
I'm going to add a colormap function that will use the GDAL color table to autogen the table between two colors.

**Comment by scisco** [comment]
fantastic 💃
