### ISSUE TITLE
Rect width/height methods assume grid spacing of 1

### ISSUE THREAD

**Issue by ircwaves** [gipit/gippy#7]
as discussed with @matthewhanson -- the width being 

    p1.x - p0.x + 1 

properly computes the width for a pixel grid where the spacing is 1.  But if the spacing is not 1 (call it *res*), then this will be **res - 1** *short* of the actual width.

**Comment by matthewhanson** [comment]
@ircwaves So far I think the rect functions have only been used in pixel space, and not used in a projected space....I think.   Although that could certainly be useful, I'm not sure where this would be a problem as it stands now.   Could you provide more detail or a use case for where this has come up as an issue?

**Comment by matthewhanson** [comment]
nm, i came across this when using Rect<double> for extents of things.   Fixed this properly by making it not add 1 and calculates the actual width, and code that used Rect<int> has been updated.

**Comment by ircwaves** [comment]
Very cool.  Thanks.  I'm running  a gipit deficit now ;)
