### ISSUE TITLE
RGB image appears as Black and White on OSX

### ISSUE THREAD

**Issue by scisco** [gipit/gippy#82]
RGB images saved with `GeoImage.save()` appears black and white on Mac's preview app. QGIS correctly shows the colored image.

**Comment by matthewhanson** [comment]
@scisco did you save this as a byte image?   Turns out the RGB labels are not something that can be set after creation, but when I create a new tif file that has 3 bands it automatically sets the ColorInterp of Red/Green/Blue (and alpha if 4 bands), but only if the dataset is Byte

**Comment by matthewhanson** [comment]
works as expected

**Comment by scisco** [comment]
Was able to set colorInterp for dtypes above uint8 outside of Gippy. This I think is still a bug.
