### ISSUE TITLE
Make GeoImage::Write more flexible

### ISSUE THREAD

**Issue by matthewhanson** [gipit/gippy#9]
So that it can accept an array that is either 

B x 1 x X x Y 
-or-
B x X x Y

**Comment by matthewhanson** [comment]
GIPPY should never return any dimension of 1.

**Comment by ircwaves** [comment]
Perhaps:
`GeoRaster.Read()` returns an `ndarray((X, Y), dtype)`
`GeoImage.Read()` returns an `ndarray((B, X, Y), dtype)`
`GeoImages.Read()` returns an `ndarray((N, B, X, Y), dtype)` where `N` is the number of images.

**Comment by ircwaves** [comment]
...And `Write` methods should expect similar shaped arrays.

**Comment by matthewhanson** [comment]
I think that's a good plan @ircwaves I think we all agree that it should never return any dimension of 1.

**Comment by ircwaves** [comment]
I'm fine with that plan, but I've just been in the habit of checking dimensions for so long, that it is second nature ;)
