### ISSUE TITLE
Installation does not work.

### ISSUE THREAD

**Issue by kostasthebarbarian** [gipit/gippy#95]
Tried:

sudo apt-get install libgdal1h gdal-bin libgdal-dev g++4.8

E: Unable to locate package g++4.8
E: Couldn't find any package by regex 'g++4.8'

Also, within a virtualenv, tried

pip install gippy -pre 

and got:

Invalid requirement: '–pre'
Traceback (most recent call last):
  File "/home/ubuntu/venv2/local/lib/python2.7/site-packages/pip/req/req_install.py", line 77, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/ubuntu/venv2/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3036, in parse
    req, = parse_requirements(s)
  File "/home/ubuntu/venv2/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2967, in parse_requirements
    raise RequirementParseError("Missing distribution spec", line)
RequirementParseError: Missing distribution spec –pre

**Comment by matthewhanson** [comment]
Hi, what OS are you running on?    If Ubuntu 14.04 or later, I think g++ might be sufficient (no version number).

With the pip install, the --pre switch needs two dashes.

Let me know if you get it working!

**Comment by matthewhanson** [comment]
I tested on a fresh Ubuntu (14.04) and updated the installation doc.
http://gippy.readthedocs.io/en/latest/install.html

The previous instructions I think were based on 12.04, but I'm going to test that out and will post 12.04 details if different (specifically I think g++4.8 is a valid package on 12.04, but on 14.04 4.8 is the default g++ package.   

@kostasthebarbarian If you still run into problems please post here, otherwise I will close the issue at the end of the day tomorrow. Thanks!

**Comment by kostasthebarbarian** [comment]
I tried in a virtualenv and failed:

(venv)ubuntu@ip-172-30-1-218:~$ pip install gippy
Collecting gippy
  Using cached gippy-0.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PIq8Yq/gippy/setup.py", line 34, in <module>
        from wheel.bdist_wheel import bdist_wheel
    ImportError: No module named wheel.bdist_wheel
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PIq8Yq/gippy/
(venv)ubuntu@ip-172-30-1-218:~$ pip install gippy --pre
Collecting gippy
  Using cached gippy-1.0.0b1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w4q_Iv/gippy/setup.py", line 41, in <module>
        from wheel.bdist_wheel import bdist_wheel
    ImportError: No module named wheel.bdist_wheel
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-w4q_Iv/gippy/

Also in the line in the docs:

$ pip install gippy –pre

it is hard to see the double dash (something wrong in the .rst format probably.)

**Comment by matthewhanson** [comment]
What platform are you running on, is it mac?   I didn't think the wheel module was used on mac.

You can install via

pip install wheel

I've got to test and update the mac install notes.  @scisco did you have any notes on what was required to run on mac?

**Comment by kostasthebarbarian** [comment]
This is Ubuntu 14.04, in a clean virtualenv.

I also tried within a conda environment and failed as well.

**Comment by matthewhanson** [comment]
I'm not sure what the problem would be.   I didn't need to do a pip install wheel so I can't replicate the problem.   After you do a pip install wheel do you get an error message?

**Comment by matthewhanson** [comment]
@kostasthebarbarian Please let me know if you were able to resolve this.   I have been unable to replicate this on a fresh 14.04 Ubuntu machine.  

If I don't hear back I will be closing the issue tomorrow, thanks.
