### ISSUE TITLE
Installation problem on Archlinux

### ISSUE THREAD

**Issue by kikislater** [gipit/gippy#98]
Hi, 

Installation seems not working on Archlinux : 

> $ python2 setup.py install
> running install
> running build_ext
> building 'gippy/libgip' extension
> creating build
> creating build/temp.linux-x86_64-2.7
> creating build/temp.linux-x86_64-2.7/GIP
> gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -IGIP -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include -I/usr/include/python2.7 -c GIP/GeoVectorResource.cpp -o build/temp.linux-x86_64-2.7/GIP/GeoVectorResource.o -fPIC -O3 -std=c++11 -Wno-maybe-uninitialized
> GIP/GeoVectorResource.cpp: Dans le constructeur ‘gip::GeoVectorResource::GeoVectorResource(std::__cxx11::string, std::__cxx11::string)’:
> GIP/GeoVectorResource.cpp:37:30: erreur : ‘Open’ is not a member of ‘OGRSFDriverRegistrar’
>          _OGRDataSource.reset(OGRSFDriverRegistrar::Open(filename.c_str()), OGRDataSource::DestroyDataSource);
>                               ^~~~~~~~~~~~~~~~~~~~
> GIP/GeoVectorResource.cpp:37:91: attention : ‘static void OGRDataSource::DestroyDataSource(OGRDataSource*)’ is deprecated [-Wdeprecated-declarations]
>  .reset(OGRSFDriverRegistrar::Open(filename.c_str()), OGRDataSource::DestroyDataSource);
>                                                                      ^~~~~~~~~~~~~~~~~
> In file included from GIP/gip/GeoVectorResource.h:28:0,
>                  from GIP/GeoVectorResource.cpp:22:
> /usr/include/ogrsf_frmts.h:245:25: note : declared here
>      static void         DestroyDataSource( OGRDataSource * ) OGR_DEPRECATED("Use GDALDataset class instead");
>                          ^~~~~~~~~~~~~~~~~
> error: command 'gcc' failed with exit status 1

I tried with pip before : 

> $ pip install gippy
> Collecting gippy
>   Using cached gippy-0.3.5.tar.gz
> Building wheels for collected packages: gippy
>   Running setup.py bdist_wheel for gippy ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_8sgx0ja/gippy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp6edpypnrpip-wheel- --python-tag cp35:
>   running bdist_wheel
>   running build_ext
>   building 'gippy/libgip' extension
>   creating build
>   creating build/temp.linux-x86_64-3.5
>   creating build/temp.linux-x86_64-3.5/GIP
>   gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -IGIP -I/usr/include/python3.5m -c GIP/tests.cpp -o build/temp.linux-x86_64-3.5/GIP/tests.o -std=c++11 -O3 -DBOOST_LOG_DYN_LINK
>   cc1plus: attention : command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>   In file included from GIP/gip/GeoImage.h:25:0,
>                    from GIP/gip/tests.h:25,
>                    from GIP/tests.cpp:23:
>   GIP/gip/GeoResource.h:32:28: erreur fatale : gdal/gdal_priv.h : Aucun fichier ou dossier de ce type
>    #include <gdal/gdal_priv.h>
>                               ^
>   compilation terminée.
>   error: command 'gcc' failed with exit status 1
>   
>   ----------------------------------------
>   Failed building wheel for gippy
>   Running setup.py clean for gippy
> Failed to build gippy
> Installing collected packages: gippy
>   Running setup.py install for gippy ... error
>     Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_8sgx0ja/gippy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wq24jaxn-record/install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build_ext
>     building 'gippy/libgip' extension
>     creating build
>     creating build/temp.linux-x86_64-3.5
>     creating build/temp.linux-x86_64-3.5/GIP
>     gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -IGIP -I/usr/include/python3.5m -c GIP/tests.cpp -o build/temp.linux-x86_64-3.5/GIP/tests.o -std=c++11 -O3 -DBOOST_LOG_DYN_LINK
>     cc1plus: attention : command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
>     In file included from GIP/gip/GeoImage.h:25:0,
>                      from GIP/gip/tests.h:25,
>                      from GIP/tests.cpp:23:
>     GIP/gip/GeoResource.h:32:28: erreur fatale : gdal/gdal_priv.h : Aucun fichier ou dossier de ce type
>      #include <gdal/gdal_priv.h>
>                                 ^
>     compilation terminée.
>     error: command 'gcc' failed with exit status 1
>     
>     ----------------------------------------
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_8sgx0ja/gippy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wq24jaxn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_8sgx0ja/gippy/

I have gdal_priv.h on my installation : 
> $ locate gdal_priv.h
> /usr/include/gdal_priv.h
> $ gdal-config --cflags
> -I/usr/include

Any suggestion ?

Sincerely,

Sylvain

**Comment by matthewhanson** [comment]
Hello Sylvain,

In the first case it looks like there might be a versioning issue of GDAL/OGR.   Can you check the gdal version?

$ gdalinfo --version

In the second case, with pip install, you are installing an older version (0.3.5) of GIPPY which has more dependencies, and is looking for the gdal header files in an include gdal/ directory (rather than just in include).

You can try
$ pip install gippy --pre

which will install the 1.0.0 beta version (pre allows installation of beta versions) rather than 0.3.5, but I suspect you may run into the same error as your first case.

**Comment by kikislater** [comment]
Hi,

Thank you for the reply.

$  gdalinfo --version
GDAL 2.0.2, released 2016/01/26

Same error as the first related. Which version of gdal is required?

**Comment by matthewhanson** [comment]
GDAL 2 is not yet supported, there's some underlying changes in OGR's handling of vector files.   It should work with any GDAL later than 1.9, I recommend 1.11, which is the version supplied on Ubuntu.

**Comment by kikislater** [comment]
Ok thank you

**Comment by matthewhanson** [comment]
@kikislater Please let me know if you were able to resolve this. If I don't hear back the issue will be closed this week.

**Comment by kikislater** [comment]
No not solve. I stay in gdal 2 since it was release last year.
May be I have to fork gippy to adapt to gdal/ogr 2 but don't have any time at this moment ...

**Comment by matthewhanson** [comment]
Thanks for the response @kikislater I am closing this out and will start a new issue for working with GDAL2.
